github.com:
    user: cdbzb
    oauth_token: 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
    git_protocol: https
    users:
        cdbzb:
            oauth_token: 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
