-- org_toc.lua
-- Generates/updates a table-of-contents org file with links to all org files in the folder

local M = {}

-- Configuration
M.config = {
  toc_filename = "index.org",  -- name of the TOC file
  toc_title = "Table of Contents",
  include_subdirs = false,  -- whether to recurse into subdirectories
  sort_alphabetically = true,
  exclude_patterns = { "^%.", "^index%.org$" },  -- patterns to exclude
}

-- Check if filename matches any exclude pattern
local function should_exclude(filename)
  for _, pattern in ipairs(M.config.exclude_patterns) do
    if filename:match(pattern) then
      return true
    end
  end
  return false
end

-- Get the title from an org file (first #+TITLE: or first headline)
local function get_org_title(filepath)
  local file = io.open(filepath, "r")
  if not file then
    return nil
  end

  for line in file:lines() do
    -- Check for #+TITLE:
    local title = line:match("^#%+TITLE:%s*(.+)$")
    if title then
      file:close()
      return title
    end
    -- Check for first headline
    local headline = line:match("^%*+%s+(.+)$")
    if headline then
      file:close()
      -- Strip TODO keywords and tags from headline
      headline = headline:gsub("^%u+%s+", "")  -- remove TODO/DONE etc
      headline = headline:gsub("%s+:%S+:$", "")  -- remove tags
      return headline
    end
  end

  file:close()
  return nil
end

-- Get all org files in directory
local function get_org_files(dir)
  local files = {}
  local handle = vim.loop.fs_scandir(dir)

  if not handle then
    return files
  end

  while true do
    local name, type = vim.loop.fs_scandir_next(handle)
    if not name then
      break
    end

    if type == "file" and name:match("%.org$") and not should_exclude(name) then
      local filepath = dir .. "/" .. name
      local title = get_org_title(filepath) or name:gsub("%.org$", "")
      table.insert(files, {
        filename = name,
        filepath = filepath,
        title = title,
      })
    elseif type == "directory" and M.config.include_subdirs and not name:match("^%.") then
      local subdir_files = get_org_files(dir .. "/" .. name)
      for _, f in ipairs(subdir_files) do
        f.filename = name .. "/" .. f.filename
        table.insert(files, f)
      end
    end
  end

  if M.config.sort_alphabetically then
    table.sort(files, function(a, b)
      return a.title:lower() < b.title:lower()
    end)
  end

  return files
end

-- Generate the TOC content
local function generate_toc_content(files)
  local lines = {
    "#+TITLE: " .. M.config.toc_title,
    "#+STARTUP: showall",
    "",
    "# Auto-generated by org_toc.lua",
    "# Last updated: " .. os.date("%Y-%m-%d %H:%M"),
    "",
  }

  for _, file in ipairs(files) do
    -- Create org-mode file link with title as description
    local link = string.format("* [[file:%s][%s]]", file.filename, file.title)
    table.insert(lines, link)
  end

  return table.concat(lines, "\n")
end

-- Main function to generate/update TOC
function M.generate_toc(opts)
  opts = opts or {}
  local dir = opts.dir or vim.fn.expand("%:p:h")
  local toc_path = dir .. "/" .. M.config.toc_filename

  local files = get_org_files(dir)

  if #files == 0 then
    vim.notify("No org files found in " .. dir, vim.log.levels.WARN)
    return
  end

  local content = generate_toc_content(files)

  local file = io.open(toc_path, "w")
  if not file then
    vim.notify("Could not write to " .. toc_path, vim.log.levels.ERROR)
    return
  end

  file:write(content)
  file:close()

  vim.notify(string.format("TOC updated: %d files in %s", #files, M.config.toc_filename), vim.log.levels.INFO)

  -- Optionally open the TOC file
  if opts.open then
    vim.cmd("edit " .. toc_path)
  end
end

-- Setup function to configure and create commands
function M.setup(opts)
  if opts then
    M.config = vim.tbl_deep_extend("force", M.config, opts)
  end

  -- Create user command
  vim.api.nvim_create_user_command("OrgToc", function(cmd_opts)
    M.generate_toc({ open = cmd_opts.bang })
  end, {
    bang = true,
    desc = "Generate org-mode table of contents (use ! to open after)",
  })

  -- Optional: create keymap
  vim.keymap.set("n", "<leader>oT", function()
    M.generate_toc({ open = true })
  end, { desc = "Generate and open org TOC" })
end

return M
